apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apple-serverless
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale:  "2"
    spec:
      containers:
        - image: docker.io/chandimsett/http-echo:latest
          imagePullPolicy: Always
#          args:
#            - "-text=apple"
          ports:
            - containerPort: 5678
