inferenceEngineServerless:
  - name: http-echo-serverless
    image: docker.io/chandimsett/http-echo:latest
    minScale: 1
  - name: http-echo-serverless2
    image: docker.io/chandimsett/http-echo:latest
    minScale: 1
BUILD_VERSION: 1
